### ISSUE TITLE
Please add support for recent versions of OpenGL and StateVar 

### ISSUE THREAD

**Issue by peti** [meteficha/Hipmunk#8]
http://packdeps.haskellers.com/feed?needle=Hipmunk

**Comment by corngood** [comment]
I just built it with StateVar 1.1, and it seems ok.  Without relaxing the constraint I was getting Hipmunk-0.2.2 from cabal, which doesn't even build correctly.

**Comment by peti** [comment]
Ping?

**Comment by meteficha** [comment]
I'm not actively working on this package anymore.  Especially since most of the changes it needs are pretty boring: upgrading deps, upgrading Chipmunk.  I'll merge and release PRs, though.

**Comment by peti** [comment]
In that case, would you mind marking the package as unmaintained (or deprecated, even) on Hackage?

**Comment by meteficha** [comment]
Maintainership is a spectrum, I'm not sure what below what level something should be marked as "unmaintained" on Hackage.  From my POV, it is maintained: I'm here talking to you, after all.  I'm just tired of chasing OpenGL changes.  I'll happily accept PR and release new versions.

**Comment by peti** [comment]
This statement 

> I'm not actively working on this package anymore.

sounds like "package is unmaintained" to me.

> I'm here talking to you, after all. 

Well, you're here talking to me about an issue I reported 4 months ago, and the response is "go fix it yourself".

Anyway, it's your choice.

**Comment by meteficha** [comment]
Sorry, closed it accidentally. 

There are many packages on Hackage that have truly been abandoned, the maintainers don't care about pull requests, etc. 

I'm sorry about taking so long to answer here.  I'd like to fix it myself but I can't justify the effort. I don't use this package for years. 

On the other hand, no one wants to step up and maintain it. I still think that some maintenership is better than none. 

If you could tell me about the advantage of the Hackage flag, I'm open to change my mind.

**Comment by peti** [comment]
I maintain 7,000+ Haskell packages in NixOS. When I notice a build error or a test suite failure on our build farm, I make an effort to report it upstream. I cannot always submit a fix, obviously, because I don't personally use all those packages, but more often than not the maintainers are quite happy to hear about the issue anyways and they fix it themselves and release a working version to Hackage.

Now, if I had known that you don't actively maintain this package, then I wouldn't have spent my spare time opening this ticket. So, having some way to know that you don't actively maintain Hipmunk any more would have been great.

**Comment by meteficha** [comment]
I understand.  I know and appreciate your hard work, and it has helped me fix errors multiple times in the past.  I've marked it "deprecated", even though it's not deprecated *per se*.

**Comment by corngood** [comment]
Here's what I've been using (#11) in case you're interested in pulling it.

**Comment by meteficha** [comment]
Thanks, @corngood!  Closing this issue.
